language: go

go:
  - tip

os:
  - linux

addons:
  ssh_known_hosts: tsvetkov.io

before_install:
  - openssl aes-256-cbc -K $encrypted_b09bc9aa8d76_key -iv $encrypted_b09bc9aa8d76_iv -in deploy-key.enc -out deploy-key -d
  - rm deploy-key.enc
  - chmod 600 deploy-key
  - mv deploy-key ~/.ssh/id_rsa 

install:
  - go get -v -u github.com/spf13/hugo

script:
  - git clone https://github.com/atsvetkov/hyde.git themes/hyde
  - hugo

after_success:
  - test $TRAVIS_BRANCH == "master"
  - cd public
  - git init    
  - git remote add deploy "deploy@tsvetkov.io:/var/www/tsvetkov.io"
  - git config user.name "Travis CI"
  - git config user.email "iammamba@gmail.com" 
  - git add .
  - git commit -m "Deployed by Travis CI"
  - git push --force deploy master
