language: go

go:
  - tip

addons:
  ssh_known_hosts: tsvetkov.io

before_script:
  - go get -u -v github.com/spf13/hugo

dd:
- openssl aes-256-cbc -K $encrypted_b09bc9aa8d76_key -iv $encrypted_b09bc9aa8d76_iv -in deploy-key.enc -out deploy-key -d

script:
  - hugo --theme=hugo_theme_robust

after_success:
  - bash deploy.sh