baseurl = "https://tsvetkov.io/"
languageCode = "en-us"
title = "Surfing the code"
theme = "hyde"
googleAnalytics = "UA-51668451-2"
disqusShortname = "tsvetkovio"
PygmentsCodeFences = true

[permalinks]
  	post = "/:year/:month/:title/"

[params]
	name = "Surfing the code"
	description = "POST /thoughts"
	disqusShortname = "tsvetkovio"

[social]
    facebook 	= "https://www.facebook.com/alex.tsvetkov.18"
    github   	= "https://www.github.com/atsvetkov"
	instagram	= "https://www.instagram.com/alexander_tsvetkov/"
	rss			= "https://tsvetkov.io/index.xml"
