baseurl = "https://surfingthecode.com/"
languageCode = "en-us"
title = "Surfing the code"
theme = "hyde"
googleAnalytics = "UA-51668451-3"
disqusShortname = "surfingthecode-com"
PygmentsCodeFences = true

[permalinks]
  	post = "/:year/:month/:title/"

[params]
	description = "with Alexander Tsvetkov"
	disqusShortname = "surfingthecode-com"

[social]
    facebook 	= "https://www.facebook.com/alex.tsvetkov.18"
    github   	= "https://www.github.com/atsvetkov"
	instagram	= "https://www.instagram.com/alexander_tsvetkov/"
	rss			= "/index.xml"
